CREATE TABLE products (
id BIGINT NOT NULL AUTO_INCREMENT,
code VARCHAR(100) NOT NULL UNIQUE,
name VARCHAR(255) NOT NULL,
description VARCHAR(1000),
image_url TEXT,
price DECIMAL(10,2) NOT NULL,
PRIMARY KEY (id)
);